version: "3.7"

services:
  classification:
    container_name: classification
    image: acrdetectaideveastus.azurecr.io/detectai-classification:${AI_BUILD_ID}
    hostname: frontend
    environment:
      - LOCAL_ENV=${LOCAL_ENV}
      - LANGUAGE_ENGINE=en
      - PORT=5000
      - DOCKER=YES
      - FRONT=YES
    ports:
      - 5000:5000
    restart: always
    networks:
      - network

  classification_en:
    container_name: classification_en
    image: acrdetectaideveastus.azurecr.io/detectai-classification-en:${AI_BUILD_ID}
    hostname: classification_en
    environment:
      - LOCAL_ENV=${LOCAL_ENV}
      - LANGUAGE_ENGINE=en
      - PORT=5100
      - DOCKER=YES
    ports:
      - 5100:5100
    restart: always
    networks:
      - network

  classification_es:
    container_name: classification_es
    image: acrdetectaideveastus.azurecr.io/detectai-classification-es:${AI_BUILD_ID}
    hostname: classification_es
    environment:
      - LOCAL_ENV=${LOCAL_ENV}
      - LANGUAGE_ENGINE=es
      - PORT=5101
      - DOCKER=YES
    ports:
      - 5101:5101
    restart: always
    networks:
      - network

  classification_it:
    container_name: classification_it
    image: acrdetectaideveastus.azurecr.io/detectai-classification-it:${AI_BUILD_ID}
    hostname: classification_it
    environment:
      - LOCAL_ENV=${LOCAL_ENV}
      - LANGUAGE_ENGINE=it
      - PORT=5102
      - DOCKER=YES
    ports:
      - 5102:5102
    restart: always
    networks:
      - network

  classification_de:
    container_name: classification_de
    image: acrdetectaideveastus.azurecr.io/detectai-classification-de:${AI_BUILD_ID}
    hostname: classification_de
    environment:
      - LOCAL_ENV=${LOCAL_ENV}
      - LANGUAGE_ENGINE=de
      - PORT=5103
      - DOCKER=YES
    ports:
      - 5103:5103
    restart: always
    networks:
      - network

  nginx:
    container_name: nginx
    image: nginx:1.25.1
    volumes:
      - ../../docker/configs/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../../docker/configs/nginx/certs:/etc/nginx/certs
    ports:
      - "8080:80"
      - "80:80"
      - "443:443"
    depends_on:
      - classification
      - classification_en
      - classification_es
      - classification_it
      - classification_de
    restart: always
    networks:
      - network

networks:
  network: