
services:

    mysql:
        image: mariadb:10.3
        container_name: mlflow_mysql_${MYSQL_PORT1}
        hostname: mlflow_mysql_${MYSQL_PORT1}
        env_file:                               # 
            - .env                              # Default '--env-file' option: $ docker-compose up -d
        ports:
            - ${MYSQL_PORT1}:3306
            - ${MYSQL_PORT2}:33060
        environment:
            - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/password1
            - MYSQL_PASSWORD=${MYSQL_PASSWORD} # /run/secrets/password1
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            #- MYSQL_PASSWORD_FILE=${MYSQL_PASSWORD} #/run/secrets/password2

        secrets:
            - password1
            - password2
        volumes:
            - database_volume:/var/lib/mysql     # production configuration (named volume)
        networks:
            - network
    phpmyadmin:
        image: phpmyadmin:latest
        container_name: mlflow_phpmyadmin_${PHPMYADMIN_PORT}
        hostname: mlflow_phpmyadmin_${PHPMYADMIN_PORT}
        depends_on:
            - mysql
        env_file:                                
            - .env                               # Default '--env-file' option: $ docker-compose up -d
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD_FILE: /run/secrets/password1
        secrets:
            - password1
        ports:
            - ${PHPMYADMIN_PORT}:80
        networks:
            - network

    mlflow:
        build:
          dockerfile: ./mlflow/Dockerfile                 # to build a root image with a system pip install of mlflow
        image: mlflow_tracker
        container_name: mlflow_tracker_${MLFLOW_PORT}
        hostname: mlflow_phpmyadmin_${MLFLOW_PORT}
        depends_on:
            - mysql
        env_file:                                
            - .env                               
            - .secrets/env-secrets               
        ports:
            - ${MLFLOW_PORT}:5000
        volumes:
            # Artifact store locally available through folder mapping:
            - /home/olonok/mlflow/mlruns:/home/olonok/mlflow/mlruns
        networks:
            - network

volumes:
    database_volume:

secrets:                                         # All secrets are stored in the container under: /run/secrets/
    password1:                                   # In this case case we use file secrets. External secrets require Swarm ()
        file: ./.secrets/mysql-root-password.txt
    password2:
        file: ./.secrets/mysql-mlflowuser-password.txt
networks:
  network: